# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokedex.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rpokedex.proto\x12\x07pokedex"\xf6\x01\n\x07Pokemon\x12\x0e\n\x06number\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08type_one\x18\x03 \x01(\t\x12\x10\n\x08type_two\x18\x04 \x01(\t\x12\r\n\x05total\x18\x05 \x01(\x04\x12\x12\n\nhit_points\x18\x06 \x01(\x04\x12\x0e\n\x06\x61ttack\x18\x07 \x01(\x04\x12\x0f\n\x07\x64\x65\x66\x65nse\x18\x08 \x01(\x04\x12\x16\n\x0especial_attack\x18\t \x01(\x04\x12\x17\n\x0fspecial_defense\x18\n \x01(\x04\x12\r\n\x05speed\x18\x0b \x01(\x04\x12\x12\n\ngeneration\x18\x0c \x01(\x04\x12\x11\n\tlegendary\x18\r \x01(\x08\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pokedex_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_POKEMON"]._serialized_start = 27
    _globals["_POKEMON"]._serialized_end = 273
# @@protoc_insertion_point(module_scope)
